FROM rust:latest AS build
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:trixie-slim
WORKDIR /app

COPY --from=build /app/target/release/products /app/server

EXPOSE 3000
CMD ["./server"]
