FROM rust:latest AS build
WORKDIR /app
COPY . .
RUN cargo build --release

FROM debian:trixie-slim
RUN apt update && apt install -y ca-certificates

WORKDIR /app

COPY --from=build /app/target/release/products /app/server

EXPOSE 3000
CMD ["./server"]
